---
title: "S&DS Final Project"
author: "The ANOVA Avengers"
date: "2023-05-06"
geometry: margin=1cm
output:
  pdf_document:
    toc: yes
    number_sections: yes
    toc_depth: 3
  word_document:
    toc: yes
    toc_depth: '3'
urlcolor: blue
---
<style type="text/css">
  body{
  font-size: 4pt;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,      ## show or suppress the code
                      include = TRUE ,      ## show or suppress the output
                      message = FALSE,      ## omit messages generated by code
                      warning = FALSE,      ## omit warnings generated by code
                      comment = NA,         ## removes the ## from in front of outputs
                      fig.align = "center", ## centers all figures
                      fig.height = 5,     ## set the default height
                      fig.weight = 5      ## set the default width
)

# load packages
library(tidyverse)
library(ggfortify)
library(ggplot2)
library(GGally)
library(ISLR)
library(Stat2Data)
library(lubridate)
library(wordcloud)
library(tidytext)
library(dplyr)
library(tidyr)
library(car)
library(boot)
library(PerformanceAnalytics)
library(corrplot)
library(olsrr)
library(leaps)
```

# Introduction

```{r}
songs <- read.csv("https://raw.githubusercontent.com/Tkota10/Spotify_Top_100-Songs/main/S%26DS_230_Spotify.csv")
```

## Data Cleaning
```{r}
# get rid of ID column
songs <- songs[,-1]

# fix column names 
names(songs) <- tolower(names(songs))
names(songs)[15] <- "streams"
names(songs)[16] <- "releasedate"

# fix release date format
songs$releasedate <- as.Date(songs$releasedate, format = "%d-%b-%y")

# create column releaseyear
songs$releaseyear <- format(as.Date(songs$releasedate), "%Y")

# filter the songs data frame to include only songs with less than 3 billion streams
songs <- subset(songs, streams < 3)

# replace 1's with "minor" and 0's with "major" in the "mode" column
songs$mode <- ifelse(songs$mode == 1, "Minor", "Major")

# code to convert data into non-scientific notation: 
songs$acousticness <- sprintf("%.5f", songs$acousticness)

# code to convert data into non-scientific notation: 
songs$instrumentalness <- sprintf("%.5f", songs$instrumentalness)

# change key from number to musical key - 0 = C, 1 = C#, etc. 
songs$key <- ifelse(songs$key == 0, "C", 
             ifelse(songs$key == 1, "C#", 
             ifelse(songs$key == 2, "D", 
             ifelse(songs$key == 3, "D#", 
             ifelse(songs$key == 4, "E", 
             ifelse(songs$key == 5, "F",
             ifelse(songs$key == 6, "F#", 
             ifelse(songs$key == 7, "G",
             ifelse(songs$key == 8, "G#", 
             ifelse(songs$key == 9, "A", 
             ifelse(songs$key == 10, "A#", 
             ifelse(songs$key == 11, "B", "Unknown"))))))))))))

#create column release month and create seasons column (Spring/Summer or Fall/Winter)
songs$releasemonth <- format(as.Date(songs$releasedate), "%B")
songs$season <- ifelse(songs$releasemonth %in% 
                         c("March", "April", "May", "June", "July", "August"), 
                       "S/S",
                    ifelse(songs$releasemonth %in% 
                             c("September", "October", "November", "December", 
                               "January", "February"), "F/W", "Unknown"))

# delete rows with NA's
songs <- na.omit(songs) 


```


*Blahh blah blah*


## Scatterplots
```{r, out.width="25%", out.height="25%"}
library(gridExtra)

plot1 <- ggplot(songs, aes(x = streams, y = energy)) +
  geom_point(col = "aquamarine4") +
  labs(x = "Streams", y = "Energy") +
  ggtitle("Scatterplot of Streams by Energy") +
  theme(plot.title = element_text(hjust = 0.5))
plot2 <- ggplot(songs, aes(x = streams, y = danceability)) +
  geom_point(col = "black") +
  labs(x = "Streams", y = "Danceability") +
  ggtitle("Scatterplot of Streams by Danceability") +
  theme(plot.title = element_text(hjust = 0.5))
plot3 <- ggplot(songs, aes(x = streams, y = loudness)) +
  geom_point(col = "orange") +
  labs(x = "Streams", y = "Loudness") +
  ggtitle("Scatterplot of Streams by Loudness") +
  theme(plot.title = element_text(hjust = 0.5))
plot4 <- ggplot(songs, aes(x = streams, y = valence)) +
  geom_point(col = "blue") +
  labs(x = "Streams", y = "Valence") +
  ggtitle("Scatterplot of Streams by Valence") +
  theme(plot.title = element_text(hjust = 0.5))
grid.arrange(plot1, plot2, plot3, plot4, ncol = 2)

cor(songs$energy, songs$streams)
cor(songs$danceability, songs$streams)
cor(songs$loudness, songs$streams)
cor(songs$valence, songs$streams)

```

```{r}
p1 <- ggplot(songs, aes(x = danceability, y = duration)) +
  geom_point(col = "chocolate") +
  labs(x = "Danceability", y = "Duration") +
  ggtitle("Scatterplot of Danceability by Duration") +
  theme(plot.title = element_text(hjust = 0.5))
p2 <- ggplot(songs, aes(x = danceability, y = loudness)) +
  geom_point(col = "orange") +
  labs(x = "Danceability", y = "Loudness") +
  ggtitle("Scatterplot of Danceability by Loudness") +
  theme(plot.title = element_text(hjust = 0.5))
p3 <- ggplot(songs, aes(x = danceability, y = valence)) +
  geom_point(col = "blue") +
  labs(x = "Danceability", y = "Valence") +
  ggtitle("Scatterplot of Danceability by Valence") +
  theme(plot.title = element_text(hjust = 0.5))
p4 <- ggplot(songs, aes(x = danceability, y = streams)) +
  geom_point() +
  labs(x = "Danceability", y = "Streams") +
  ggtitle("Scatterplot of Danceability by Streams") +
  theme(plot.title = element_text(hjust = 0.5))
grid.arrange(p1, p2, p3, p4, ncol = 2)

cor(songs$danceability, songs$duration)
cor(songs$danceability, songs$loudness)
cor(songs$danceability, songs$valence)
cor(songs$danceability, songs$streams)

```



## Boxplots / summary statistics / t.tests
```{r}
plot11 <- ggplot(songs, aes(x = mode, y = streams, fill = mode)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Mode", y = "Streams") +
  ggtitle("Boxplot of Streams by Mode") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cyan1", "cornsilk4"))
plot22 <- ggplot(songs, aes(x = mode, y = energy, fill = mode)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Mode", y = "Energy") +
  ggtitle("Boxplot of Energy by Mode") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cyan1", "cornsilk4"))
plot33 <- ggplot(songs, aes(x = mode, y = danceability, fill = mode)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Mode", y = "Danceability") +
  ggtitle("Boxplot of Danceability by Mode") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cyan1", "cornsilk4"))
plot44 <- ggplot(songs, aes(x = mode, y = valence, fill = mode)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Mode", y = "Valence") +
  ggtitle("Boxplot of Valence by Mode") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cyan1", "cornsilk4"))
grid.arrange(plot11, plot22, plot33, plot44, ncol = 2)

(test1 <- t.test(songs$streams ~ songs$mode, conf.level = 0.95))
(test4 <- t.test(songs$danceability ~ songs$mode, conf.level = 0.95))
(test6 <- t.test(songs$energy ~ songs$mode, conf.level = 0.95))
(test8 <- t.test(songs$valence ~ songs$mode, conf.level = 0.95))

by(songs$streams, songs$mode, summary)
by(songs$energy, songs$mode, summary)
by(songs$danceability, songs$mode, summary)
by(songs$valence, songs$mode, summary)
```


```{r}
plot10 <- ggplot(songs, aes(x = season, y = streams, fill = season)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Seasons", y = "Streams") +
  ggtitle("Boxplot of Streams by Season") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cadetblue1", "coral"))
plot12 <- ggplot(songs, aes(x = season, y = energy,
                            fill = season)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Seasons", y = "Energy") +
  ggtitle("Boxplot of Energy by Season") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cadetblue1", "coral"))
plot13 <- ggplot(songs, aes(x = season, y = danceability,
                            fill = season)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Seasons", y = "Danceability") +
  ggtitle("Boxplot of Danceability by Season") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cadetblue1", "coral"))
plot14 <- ggplot(songs, aes(x = season, y = valence,
                            fill = season)) +
  geom_boxplot(outlier.colour = "red",
        outlier.shape = 2,
        outlier.size = 3) +
  stat_summary(fun = "median",
               geom = "point",
               shape = 21,
               size = 3,
               fill = "white",
               color = "black") +
  stat_summary(fun = "median",
               geom = "text",
               size = 3,
               aes(label = paste0("Median = ", round(..y.., 2))),
               vjust = -1) +
  labs(x = "Seasons", y = "Valence") +
  ggtitle("Boxplot of Valence by Season") +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("cadetblue1", "coral"))
grid.arrange(plot10, plot12, plot13, plot14, ncol = 2)

(test1 <- t.test(songs$streams ~ songs$season, conf.level = 0.95))
(test3 <- t.test(songs$energy ~ songs$season, conf.level = 0.95))
(test4 <- t.test(songs$danceability ~ songs$season, conf.level = 0.95))
(test8 <- t.test(songs$valence ~ songs$season, conf.level = 0.95))
```
## Histograms / QQplots / 
```{r}
hist(songs$streams, breaks = 30,
     main = "Histogram of Streams (in Billions)",
     xlab = "Streams (in Billions)",
     col = "plum")
```
## Correlations / Plots
```{r}
source("http://www.reuningscherer.net/s&ds230/Rfuncs/regJDRS.txt")
songs.cor <- songs[ , c("danceability", "duration", "energy", "loudness", "speechiness", "liveness", "valence", "tempo", "streams")]
  
names(songs)

sigcorr <- cor.mtest(songs.cor, conf.level = .95)
corrplot.mixed(cor(songs.cor), lower.col="black", upper = "ellipse", tl.col = "black", number.cex=.7, 
                tl.pos = "lt", tl.cex=.7, p.mat = sigcorr$p, sig.level = .05)

```

## Bootstraps
```{r}
set.seed(230)

(cor1test <- cor.test(songs$energy, songs$danceability, conf.level = .95))

N <- nrow(songs)

n_samp <- 10000

corResults <- rep(NA, n_samp)

for(i in 1:n_samp){
  s <- sample(1:N, N, replace = T)
  fakedata <-  songs[s, ]
  corResults[i] <- cor(fakedata$energy, fakedata$danceability)
}

(ci_r <- quantile(corResults, c(.025, .975)))

hist(corResults, xlab = "Sample Correlation",
     main = "Bootstrapped Correlation",
     col = "darkslategray1",
     breaks = 50)
abline(v = ci_r, lwd = 3, col = "midnightblue")
abline(v = cor1test$conf.int, lwd = 3, col = "gray48", lty = 2)
legend("topleft", c("Theoretical CI", "Boot CI"), 
       lwd = 3, col = c("gray48", "midnightblue"), lty = c(2, 1))
```
## Permutation Tests
```{r}
set.seed(230)

N <- 10000

diff <- rep(NA, N)

for(i in 1:N){
  fakeseason <- sample(songs$season)
  diff[i] <- median(songs$danceability[fakeseason == "S/S"]) - 
    median(songs$danceability[fakeseason == "F/W"])
}

hist(diff,
     main = "Permuted Sample Median Differences in Danceability",
     xlab = "Danceability",
     col = "aquamarine",
     breaks = 20)

actualdiff <- median(songs$danceability[songs$season == "S/S"]) - 
    median(songs$danceability[songs$season == "F/W"])

text(actualdiff - .01, 800, paste("Actual Diff in Medians =", round(actualdiff,2)), srt = 90)
abline(v = actualdiff,
       col = "maroon",
       lwd = 3)

mean(abs(diff) >= abs(actualdiff))
```

```{r}
library(PerformanceAnalytics)

#Here is a cool way to look for non-linearity, get correlation, make histograms all at once.

chart.Correlation(songs.cor, histogram = TRUE, pch = 19)
```

## Multiple Regresssions
```{r, echo = FALSE}
mod1 <- regsubsets(danceability ~ ., data = songs.cor, nvmax = 8)
mod1sum <- summary(mod1)
mod1sum$which

which.max(mod1sum$rsq)
names(songs.cor)[mod1sum$which[which.max(mod1sum$rsq), ]][-1]
songstemp <- songs.cor[ ,mod1sum$which[which.max(mod1sum$rsq), ]]
summary(lm(danceability ~ ., data = songstemp))
plot(mod1, main = "Best Model According to R-squared", scale = "r2")

which.max(mod1sum$adjr2)
names(songs.cor)[mod1sum$which[which.max(mod1sum$adjr2), ]][-1]
songstemp <- songs.cor[, mod1sum$which[which.max(mod1sum$adjr2), ]]
summary(lm(danceability ~ ., data = songstemp))
plot(mod1, main = "Best Model According to Adjusted R-squared", scale="adjr2")

which.min(mod1sum$bic)
names(songs.cor)[mod1sum$which[which.min(mod1sum$bic), ]][-1]
songstemp <- songs.cor[,mod1sum$which[which.min(mod1sum$bic), ]]
summary(lm(danceability ~ ., data = songstemp))
plot(mod1, main = "Best Model According to BIC", scale="bic")

songstemp <- (songs.cor)[ , mod1sum$which[which.min(mod1sum$bic), ]]
modfin <- lm(danceability ~ ., data = songstemp)
summary(modfin)
modnum <- which.min(mod1sum$bic) 
names(which(mod1sum$which[modnum,] == TRUE))
mod1sum$bic[which.min(mod1sum$bic)]
```

```{r}
modnum <- min(c(1:length(mod1sum$cp))[mod1sum$cp <= c(1:length(mod1sum$cp)) + 1])
names(songs.cor[mod1sum$which[modnum,]][-1])
songstemp <- songs.cor[,mod1sum$which[modnum,]]
summary(lm(danceability ~ ., data = songs.cor))

lm <- lm(danceability ~ valence + speechiness + duration, data = songs.cor)
summary(lm)

# The multiple R-squared for this model is 0.1429, indicating that the models explain around 14% of the variance in danceability, which is relatively low. Regarding the significance of the independent variables, valence is the only variable that is significant in both models with a p-value less than 0.05. The coefficient for valence is positive, indicating that as valence increases, danceability tends to increase. However, the coefficients for speechiness and duration are not significant in the second model. The p-value for speechiness is 0.13059, which is greater than 0.05, and the p-value for duration is 0.18642. Overall, the results suggest that valence is the most important variable in predicting danceability, while speechiness and duration may not be as significant. 

myResPlots2(lm)

```



```{r}
attach(songs)

#Trying 2-way ANOVA of Mode and Season on Danceability
par(mar = c(7, 5, 4, 2))
boxplot(danceability ~ mode + season, col = 'red', las = 2, cex = .5, xlab = "")

interaction.plot(mode, season, danceability, type = 'b', lwd = 3, col = c('red','blue','black'), main = "Interaction Plot of Mode and Season Type")

danceaov <- aov(danceability ~ mode + season + mode*season)
summary(danceaov)
dancelm <- lm(danceability ~ mode + season + mode*season -1)
summary(dancelm)

combo <- as.factor(paste(mode, season))
danceaov2 <- aov(danceability ~ combo)
summary(danceaov2)
summary.lm(danceaov2)

par(mar = c(5, 15, 4, 2))
plot(TukeyHSD(danceaov2), las = 1)
```



#








